### ISSUE TITLE
Add support for VM ownership (user permission) change

### ISSUE THREAD

**Issue by chandidas** [IBM-tfproviders/terraform-provider-vsphere#15]
**_Terraform should provide support, so that 'Privileged' user can change/assign ownership (i.e. add permission to other user) of virtual machine resource._**

A new configuration section, given below, is used to specify the ownership.

```
permission  {
    role = 'Admin'
    user_name = 'aRegularUser'
}

role -> one of the existing roles pre-created by administrator
user_name -> name of the user going to own this resource
```

Use cases to be supported by this issue:
- In create VM operation, if 'permission' section is configured, the user will get permission to access the VM resource as per configured role.
- In update VM operation, if 'permission' is configured, user will get permission
- In update VM operation, if 'permission' section is removed, user permission will be revoked
- In update VM operation, if 'permission' section is modified, user permission will be modified accordingly.

**Comment by santoshananda** [comment]
Closed by pull request https://github.com/IBM-tfproviders/terraform-provider-vsphere/pull/17
