### ISSUE TITLE
Cannot resize the disk - root disk resize fails and other disks gets recreated

### ISSUE THREAD

**Issue by rachappag** [IBM-tfproviders/terraform-provider-vsphere#2]
The disk resize attempts to recreate the disk with new size - Delete the existing disk and create new disk with new size.
 
Hence other than root(boot) disk resize, endup loosing data due to disk recreation.
Root disk resize fails due to vpshere API error ( boot disk deletion not allowed on running VM )

**Comment by santoshananda** [comment]
Terraform today delete-creates the disk, that it created, when the disk is resized. This has been handled and resize operation just extends the existing disk instead of delete-creating it.

**Comment by santoshananda** [comment]
Closed by pull request https://github.com/IBM-tfproviders/terraform-provider-vsphere/pull/16
